# Generated by Django 4.1.3 on 2022-12-07 01:23

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('dni', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('imagen_usuario', models.ImageField(blank=True, null=True, upload_to='imagenes_usuarios')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_matriculacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_baja', models.DateField(blank=True, default=None, null=True)),
                ('is_administador', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_Examen', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_Examen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('tipo_licencia', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_Tema', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_Pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta_Falsa_1', models.TextField()),
                ('respuesta_Falsa_2', models.TextField(blank=True, null=True)),
                ('respuesta_Correcta', models.TextField()),
                ('imagen_pregunta', models.ImageField(blank=True, null=True, upload_to='imagenes_preguntas')),
                ('descripcion_adicional', models.TextField(blank=True, null=True)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoescuela.permiso')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoescuela.tema')),
            ],
        ),
        migrations.CreateModel(
            name='Examen_Usuario',
            fields=[
                ('id_Examen_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('respuestas_Usuario', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=None, size=None)),
                ('id_preguntas_falladas', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=None, null=True, size=None)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha', models.DateField()),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoescuela.examen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='permiso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoescuela.permiso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
