# Generated by Django 4.1.3 on 2022-11-25 04:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoescuela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen_usuario',
            name='id_preguntas_falladas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=None, size=None),
        ),
    ]
