# Generated by Django 4.1.3 on 2022-11-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoescuela', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temas',
            new_name='Tema',
        ),
    ]
