# Generated by Django 4.1.3 on 2022-12-09 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoescuela', '0002_examen_preguntas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen_usuario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
