# Generated by Django 4.1.3 on 2022-11-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoescuela', '0003_alter_permiso_tipo_licencia_alter_usuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='precio',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
