# Generated by Django 4.1.3 on 2022-11-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoescuela', '0003_alter_examen_usuario_id_preguntas_falladas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen_usuario',
            name='fecha',
            field=models.DateField(),
        ),
    ]
