# Generated by Django 4.1.3 on 2022-12-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('autoescuela', '0004_remove_examen_usuario_id_preguntas_falladas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
