# Generated by Django 4.1.3 on 2022-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoescuela', '0004_alter_examen_usuario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='imagen_pregunta',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_preguntas'),
        ),
    ]
