# Generated by Django 4.1.3 on 2022-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoescuela', '0004_remove_examen_usuario_id_preguntas_falladas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
