# Generated by Django 4.1.3 on 2022-11-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoescuela', '0005_alter_pregunta_imagen_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta_Falsa_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_usuarios'),
        ),
    ]
