# Generated by Django 4.1.3 on 2022-12-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoescuela', '0005_alter_usuario_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_administador',
            new_name='is_administrador',
        ),
    ]
